# Generated by Django 2.2.7 on 2019-11-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
