# Generated by Django 2.2.7 on 2019-11-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20191127_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='stage',
            field=models.CharField(choices=[('Development', 'Development'), ('Testing', 'Testing'), ('Production', 'Production')], default='Development', max_length=11),
        ),
    ]
